### PR TITLE
Switch to the higher-level fbp-client library

### LINKED ISSUE #11: Handle FBP protocol error messages
Right now they are silently ignored.

### LINKED ISSUE #12: Missing timeouts for protocol operations
Either in runner.coffee or in protocol.coffee. For startNetwork, stopNetwork, sendPacket etc.
Together with #11, probably should be put in a general facility to ensure consistent behavior.

runner must respect the timeouts set in the spec files, and report them.

### LINKED ISSUE #71: Tests times out if sending only on error
It is conventional to use a port named `error` to send errors, for instance in NoFlo components.
When causing errors, then the graph/component only sends on `error` - not the port for success (which fbp-spec is checking).
In this case we never receive any data (cause not listening for error) - and instead time out.
If we instead also automatically listened to `error` (if existing), we could check it and give a much more helpful error message.

### LINKED ISSUE #72: Error if process-error is sent
Only NoFlo implements this right now, but indicates an (unexpected) Exception. Normally these should be sent to error port (#71) but some components don't do this - and besides, bugs happen.

### LINKED ISSUE #118: No error on permission problems
To reproduce:

* Run `noflo-nodejs --register=false` without `--secret` set
* Run `fbp-spec` against it

Expected: Clear error explaining the permissions issue
Actual: Hangs forever without any output or warning

Related to #11

### LINKED ISSUE #136: Handle network errors
Currently fbp-spec just hangs if there is a network error, in this case related to starting the fixture graph:

```
 fbp-spec:runner:received network error { message: 'Component CreateDataType not available with base /home/bergie/Projects/big-iot/bigiot-bridge',
```

Related to #72

### LINKED ISSUE #137: Error if runtime crashes
Right now it seems fbp-spec doesn't notice that it got disconnected from the runtime. This should cause the suite to fail instead of hang

### PR DESCRIPTION
**Pull request by bergie**
This way we get a nice Promise API for interacting with the runtime.

However, this is likely a breaking change since fbp-client actually validates all responses from the runtime. Some runtimes will have problems with this.

Fixes #137
Fixes #136 
Fixes #118 
Fixes #72 
Fixes #71
Fixes #12
Fixes #11

### CODE REVIEW

File: src/protocol.coffee [hunk 1]
```diff
@@ -1,188 +1,99 @@
...
 
-  waitForStopped = (status) ->
-    debug 'stop: runtime status change', status
-    if not status.running
-      runtime.removeListener 'execution', waitForStopped
-      return callback null
-  runtime.on 'execution', waitForStopped
-
-  runtime.sendNetwork 'stop',
+  client.protocol.network.start(
```
Comment (jonnor) [inline src/protocol.coffee]: Uhm, this should be .stop()?

File: src/protocol.coffee [hunk 2]
```diff
@@ -1,188 +1,99 @@
...
+  return
 
 exports.sendPackets = (client, graphId, packets, callback) ->
   debug 'sendpackets', graphId, packets
 
-  for port, payload of packets
-    client.sendRuntime 'packet',
+  Promise.all(Object.keys(packets).map((port) ->
+    return client.protocol.runtime.packet
       event: 'data'
```
Comment (jonnor) [inline src/protocol.coffee]: Does this work with runtimes that don't send packetsent ACK?

File: src/runner.coffee [hunk 3]
```diff
@@ -1,26 +1,17 @@
...
-    debugReceived 'graph', command, payload
-  client.on 'network', ({command, payload}) ->
-    debugReceived 'network', command, payload
-  client.on 'runtime', ({command, payload}) ->
-    debugReceived 'runtime', command, payload
-  client.on 'component', ({command, payload}) ->
-    debugReceived 'component', command, payload
-  client.on 'execution', (status) ->
-    debugReceived 'execution', status
+  client.on 'signal', ({protocol, command, payload}) ->
```
Comment (jonnor) [inline src/runner.coffee]: When does this fire? On any message coming from runtimes, or just those that are not responses?

File: src/runner.coffee [hunk 4]
```diff
@@ -119,56 +111,64 @@ sendMessageAndWait = (client, currentGraph, inputData, expectData, callback) ->
...
-    isOnline = () =>
-      connected = @client.isConnected()
-      return if connected then Promise.resolve() else Promise.reject new Error 'Not connected to runtime'
-    tryConnect = () =>
-      debug 'trying to connect'
-      @client.connect() # does not always emit an event, so we don't bother checking any
-      return Promise.resolve()
-    return common.retryUntil(tryConnect, isOnline, timeBetweenAttempts, attempts).asCallback callback
+      debugReceivedMessages @client
+      @client.on 'network', ({command, payload}) ->
```
Comment (jonnor) [inline src/runner.coffee]: Does this event still exist?

File: spec/mochacompat.coffee [hunk 5]
```diff
@@ -33,20 +21,24 @@ setupAndConnect = (options, callback) ->
...
+    return
+  return
 
 runAllComponentTests = (ru, callback) ->
   state = null
   onUpdate = (s) ->
     state = s
   ru.connect (err) ->
-    return done err if err
+    return callback err if err
```
Comment (jonnor) [inline spec/mochacompat.coffee]: Why this change? Seems unrelated

Comment (bergie) [reply spec/mochacompat.coffee]: It _is_ unrelated, but while working on this I hit these error cases. And there is no `done` there.

File: src/runner.coffee (hunk 3 above)
Comment (bergie) [reply src/runner.coffee]: Any that are not responses, see https://github.com/flowbased/fbp-client#signals

File: src/runner.coffee (hunk 4 above)
Comment (bergie) [reply src/runner.coffee]: Yes, see https://github.com/flowbased/fbp-client#signals

File: src/protocol.coffee (hunk 2 above)
Comment (bergie) [reply src/protocol.coffee]: Yes, assuming that they don't claim to be protocol version 0.7 or above

https://github.com/flowbased/fbp-client/blob/master/lib/adapter/0_x.js#L136

**Comment by bergie** [comment]
@jonnor build is green now, had to do some polyfilling tricks to get the ES6 code working in PhantomJS

**Comment by jonnor** [comment]
@bergie does this work with noflo-nodejs in latest release?

**Comment by jonnor** [comment]
The code looks fine, but would like to test with Microflo or msgflo

**Comment by bergie** [comment]
@jonnor fbp-client itself is tested with noflo-nodejs, so that part should be fine. I would imagine there will be failures with other runtimes until their responses conform to the fbp-protocol spec (NoFlo also had some problems there)

**Comment by bergie** [comment]
Just tried against the fbp-specs in [noflo-geo](https://github.com/noflo/noflo-geo), and everything worked as expected

**Comment by bergie** [comment]
@jonnor improved error handling above, was testing against noflo-geo with some interesting errors like typos in component source

**Comment by jonnor** [comment]
@bergie hangs forever for runtimes not sending `packetsent` ACK. Protocol version: '0.4'

**Comment by bergie** [comment]
@jonnor sounds like we have a packet that doesn't pass validation. Need to add listening for `protocolError` messages.

**Comment by jonnor** [comment]
What do you mean packet missing validation? There was no `packetsent` message at all..

When sending an invalid message there it errors and tears down the graph.

When sending what looks-to-be-valid message, it hangs again.

**Comment by jonnor** [comment]
Actually when sending invalid it fails the first test, continioues to execute next test and then tearsdown.

**Comment by bergie** [comment]
@jonnor I tried again (by making noflo-runtime-base not send `packetsent` and reporting lower protocol version), and it worked as expected.

fbp-client 0.2.1 adds better error messages for observed protocol errors etc, that could help here.

After this, the main "hanging" could be that we're waiting for `runtime:packet` (or protocol error, or `network:error` or `network:processerror`). If none of these happens, we'll hang. Should maybe add timeout?

**Comment by bergie** [comment]
If that doesn't help, run with `DEBUG="fbp-client:observer,fbp-client:adapter:*"` so we see what's happening

**Comment by jonnor** [comment]
It seems that the observer mechanism swallows protocol validation errors?

**Comment by jonnor** [comment]
There is a bug in the schemas, I get `Runtime sent invalid payload for network data: data.payload should NOT have additional properties` for message
``` {
   src: { node: 'testee', port: 'out' },
   tgt: { node: 'testee', port: 'in' },
   data: 1000,
  type: 'Integer',
  graph: 'fixture.1s5I7DbKVp',
  id: 'dummy' 
}```

https://flowbased.github.io/fbp-protocol/#network-data does not list any attribute for sending the actual data

**Comment by jonnor** [comment]
Turns out problem was the 'type' property, not 'data'. So data is in the schemas, just not rendered in the docs for some reason.

**Comment by bergie** [comment]
@jonnor with fbp-client 0.2.1 we should get the protocol validation errors with observers.

**Comment by jonnor** [comment]
Got MicroFlo to pass, see above PR. MsgFlo still needs to be tested/fixed
